### PR TITLE
feat: remove lab.waku.org related examples

### PR DESCRIPTION
**Pull request by weboko**

### CODE REVIEW

**Comment by weboko** [comment]
@hackyguru @vpavlin, please, review.

**Comment by danisharora099** [comment]
@waku-org/eco-dev we intend to move web-chat to https://github.com/waku-org/lab.waku.org -- please feel free to decide the examples you would prefer to keep within examples.

**Comment by vpavlin** [comment]
Looks good to me. I think it is ok to remove web-chat from example.waku.org - we don't want people to build unencrypted chat apps anyway:)

**Review by vpavlin — APPROVED** [review]

**Comment by hackyguru** [comment]
+1, it's better to remove web-chat from examples

**Review by hackyguru — APPROVED** [review]

**Comment by weboko** [comment]
@fryorcraken need help with dropping required steps of the examples that will be removed. I don't have needed access

**Comment by fryorcraken** [comment]
@weboko done

**Pull request merged**
